In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, KFold,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report

In [16]:
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

In [9]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(url, names=names)
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [10]:
array = dataframe.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [11]:
x = array[:,0:8]
y = array[:,8]
x.shape, y.shape

((768, 8), (768,))

In [12]:
seed = 7
kfold = KFold(n_splits=10, random_state=seed)
model = LogisticRegression()
scoring = ['accuracy','neg_log_loss','roc_auc',]

In [23]:
for score in scoring:
    results = cross_val_score(model, x, y, cv=kfold, scoring=score)
    results
    print("Accuracy with %s scorring: %.3f (with standard dev: %.3f)" % (score,results.mean(), results.std()))
   

Accuracy with accuracy scorring: 0.770 (with standard dev: 0.048)
[[448  52]
 [121 147]]
Accuracy with neg_log_loss scorring: -0.493 (with standard dev: 0.047)
[[448  52]
 [121 147]]
Accuracy with roc_auc scorring: 0.823 (with standard dev: 0.041)
[[448  52]
 [121 147]]


In [25]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier,BaggingClassifier,GradientBoostingClassifier

In [57]:
lr =LogisticRegression()
rf= RandomForestClassifier(n_estimators=100)
kn= KNeighborsClassifier()
ad= AdaBoostClassifier()
bg= BaggingClassifier()
gb = GradientBoostingClassifier()

In [68]:
model = [lr,rf,kn,ad,bg,gb]

In [69]:
for model in model:
    model.fit(x,y)
    pred=model.predict(x)
    print(model)
    print("Accuracy : %.3f " % (metrics.accuracy_score(y,pred)))
    print("roc auc : %.3f " % (metrics.roc_auc_score(y,pred)))
    print("log loss : %.3f " % (metrics.log_loss(y,pred)))
    print(confusion_matrix(y, pred))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracy : 0.775 
roc auc : 0.722 
log loss : 7.780 
[[448  52]
 [121 147]]
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)
Accuracy : 0.993 
roc auc : 0.991 
log loss : 0.225 
[[500   0]
 [  5 263]]
KNeighborsClassifier(algorithm='aut

In [75]:
rf=RandomForestClassifier(n_estimators=100,max_depth=12,oob_score=True)
rf.fit(x,y)
pred=rf.predict(x)
print(model)
print("Accuracy : %.3f " % (metrics.accuracy_score(y,pred)))
print("roc auc : %.3f " % (metrics.roc_auc_score(y,pred)))
print("log loss : %.3f " % (metrics.log_loss(y,pred)))
print(confusion_matrix(y, pred))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
Accuracy : 1.000 
roc auc : 1.000 
log loss : 0.000 
[[500   0]
 [  0 268]]


[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


In [70]:
RandomForestClassifier(n_estimators=100)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [71]:
lr.decision_function

<bound method LinearClassifierMixin.decision_function of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)>

In [72]:
lr.decision_function

<bound method LinearClassifierMixin.decision_function of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)>